apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-mem-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
  #name: petclinic-mem-hpa
#spec:
  #maxReplicas: 5
  #minReplicas: 1
  #scaleTargetRef:
    #apiVersion: extensions/v1beta1
    #kind: Deployment
    #name: petclinic-deployment
  #metrics:
  #- type: Resource
    #resource:
      #name: memory
      #targetAverageUtilization: 50
